In [1]:
from sklearn.datasets import load_digits
from sklearn.feature_selection import SelectKBest, chi2, f_classif, mutual_info_classif

x, y = load_digits(return_X_y=True)
x.shape

(1797, 64)

In [2]:
import numpy as np
print(x[:2])

[[ 0.  0.  5. 13.  9.  1.  0.  0.  0.  0. 13. 15. 10. 15.  5.  0.  0.  3.
  15.  2.  0. 11.  8.  0.  0.  4. 12.  0.  0.  8.  8.  0.  0.  5.  8.  0.
   0.  9.  8.  0.  0.  4. 11.  0.  1. 12.  7.  0.  0.  2. 14.  5. 10. 12.
   0.  0.  0.  0.  6. 13. 10.  0.  0.  0.]
 [ 0.  0.  0. 12. 13.  5.  0.  0.  0.  0.  0. 11. 16.  9.  0.  0.  0.  0.
   3. 15. 16.  6.  0.  0.  0.  7. 15. 16. 16.  2.  0.  0.  0.  0.  1. 16.
  16.  3.  0.  0.  0.  0.  1. 16. 16.  6.  0.  0.  0.  0.  1. 16. 16.  6.
   0.  0.  0.  0.  0. 11. 16. 10.  0.  0.]]


In [3]:
print(np.unique(y))

[0 1 2 3 4 5 6 7 8 9]


In [4]:
sb = SelectKBest(score_func=chi2, k=20)
x_new = sb.fit_transform(x, y)
x_new.shape

(1797, 20)

In [5]:
# get_support() : 어떤 특성변수가 선택(True)되었는지 파악

sb.get_support()

array([False, False, False, False, False,  True,  True, False, False,
       False, False, False, False,  True, False, False, False, False,
       False,  True,  True,  True, False, False, False, False,  True,
       False,  True, False,  True, False, False,  True,  True, False,
       False, False, False, False, False,  True,  True,  True,  True,
       False,  True, False, False, False, False, False, False, False,
        True, False, False, False,  True, False, False,  True,  True,
       False])

In [6]:
# scores_ : 각 특성변수의 x^2 값

sb.scores_

array([          nan,  811.90700411, 3501.28249552,  698.9252572 ,
        438.52969882, 3879.81925999, 3969.45823205, 1193.5608181 ,
         24.79521396, 2953.83108764, 2583.65198939,  388.24205944,
        824.69094853, 3676.48924765, 1983.5796061 ,  597.24198237,
          8.95886124, 1924.21690377, 2409.27140681, 3556.31594594,
       4871.94194551, 4782.19921618, 2155.17378998,  376.76583333,
          7.90090158, 2471.82418401, 4515.48149826, 2986.64314847,
       3724.09567634, 3208.64686641, 5138.07412439,   35.71270718,
                 nan, 5688.25079535, 5262.46646904, 3165.0605867 ,
       3231.63943369, 2532.99695611, 3288.81403655,           nan,
        142.85082873, 3863.85787901, 6416.0867248 , 5448.25154235,
       4079.73153383, 2134.02540236, 4486.34097862,  313.53898127,
         70.39927392,  449.72327313, 2801.97224468, 1527.54519627,
       1653.15892311, 3073.99803898, 5251.21748723,  683.88227339,
          9.15254237,  851.06791492, 3800.2473108 ,  730.92975

In [7]:
# pvalues_ : 각 특성변수의 p-value 출력

sb.pvalues_

array([            nan, 5.81310493e-169, 0.00000000e+000, 1.17740541e-144,
       8.11314242e-089, 0.00000000e+000, 0.00000000e+000, 2.97727113e-251,
       3.20626273e-003, 0.00000000e+000, 0.00000000e+000, 4.41344943e-078,
       1.02825052e-171, 0.00000000e+000, 0.00000000e+000, 8.18335060e-123,
       4.41080315e-001, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 1.23435651e-075,
       5.44163062e-001, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 4.45801029e-005,
                   nan, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000,             nan,
       2.65875300e-026, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 3.49452723e-062,
       1.27145348e-011, 3.28604761e-091, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0

### 선택된 30개의 특성변수를 PCA를 통해 3개의 차원으로 축소하고 이를 3D 시각화를 통해 살펴보기

In [8]:
!pip install plotly

In [9]:
from sklearn.pipeline import make_pipeline
from sklearn.decomposition import PCA
import pandas as pd
import plotly.express as px

In [10]:
md1 = make_pipeline(SelectKBest(k=30), PCA(n_components=3))
x_new = md1.fit_transform(x, y)

/usr/local/lib/python3.7/dist-packages/sklearn/feature_selection/_univariate_selection.py:114: UserWarning:

Features [ 0 32 39] are constant.

/usr/local/lib/python3.7/dist-packages/sklearn/feature_selection/_univariate_selection.py:115: RuntimeWarning:

invalid value encountered in true_divide



In [12]:
# 3개로 차원축소된 특성변수를 DataFrame으로 pandas 데이터를 만들고 있음.

df1 = pd.DataFrame({'X': x_new[:, 0], 'Y':x_new[:, 1], 'Z':x_new[:, 2], 'C': y})
df1.head()

X          Y          Z  C
0   0.276542  21.055682 -12.078735  0
1   3.803025 -20.682804   8.283811  1
2   2.109440  -6.278095   2.483489  2
3 -12.257130   4.399777  14.436265  3
4  21.243526  -0.852420  -1.783829  4

In [13]:
# Plotly.express를 이용한 3D 시각화
# 3개의 특성변수와 클래스(color = 'C'로 지정)를 보여주고 있음.

# 10개의 숫자범주를 3개의 특성변수로 구별하기에는 문제가 있어 보임.

fig = px.scatter_3d(df1, x='X', y='Y', z='Z', color='C')
fig.show()

In [14]:
# 비선형 PCA 
# kernelPCA를 이용하여 30개의 특성변수를 6개의 특성변수로 차원 축소
# 이 중 첫 3개의 PCA를 이용하여 그림을 그리면 숫자 1과 숫자 6을 쉽게 구분할 수 있음.

from sklearn.pipeline import make_pipeline
from sklearn.decomposition import KernelPCA
import pandas as pd
import plotly.express as px

md2 = make_pipeline(SelectKBest(k=30), KernelPCA(kernel='rbf', n_components=6))
x_new2 = md2.fit_transform(x, y)

/usr/local/lib/python3.7/dist-packages/sklearn/feature_selection/_univariate_selection.py:114: UserWarning:

Features [ 0 32 39] are constant.

/usr/local/lib/python3.7/dist-packages/sklearn/feature_selection/_univariate_selection.py:115: RuntimeWarning:

invalid value encountered in true_divide



In [15]:
df2 = pd.DataFrame({'X': x_new2[:, 0], 'Y': x_new2[:, 1], 'Z': x_new2[:, 2], 'C' : y})
df2.head()

X         Y         Z  C
0 -0.004879 -0.004892 -0.013003  0
1 -0.001904 -0.000930 -0.002036  1
2 -0.001876 -0.000907 -0.001985  2
3 -0.001904 -0.000926 -0.002028  3
4 -0.001874 -0.000906 -0.001983  4

In [16]:
fig = px.scatter_3d(df2, x='X', y='Y', z='Z', color='C')
fig.show()

In [17]:
# 6개의 특성변수 중 나머지 3개의 축으로 그림을 그린다
# -> 0, 1, 2를 구별할 수 있는 특성변수임을 보여주고 있음.

# PCA를 통해 분류를 쉽게 할 수 있는 새로운 특성변수를 만들 수 있다.

df3 = pd.DataFrame({'X': x_new2[:, 3], 'Y': x_new2[:, 4], 'Z': x_new2[:, 5], 'C':y})
fig = px.scatter_3d(df3, x='X', y='Y', z='Z', color='C')
fig.show()