### 1. 제5장의 wine data를 이용하여 linear, quadratic 그리고 naive Bayesian을 적용하여 그 결과를 비교하고 해석하라.

In [3]:
import numpy as np
import pandas as pd

dat_wine = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data', header=None)

In [4]:
dat_wine.head()

0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [5]:
dat_wine.tail()

0      1     2     3     4    5     6     7     8     9     10    11  \
173   3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.7  0.64   
174   3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.3  0.70   
175   3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.2  0.59   
176   3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.3  0.60   
177   3  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.2  0.61   

       12   13  
173  1.74  740  
174  1.56  750  
175  1.56  835  
176  1.62  840  
177  1.60  560

In [6]:
dat_wine.columns = ['class label',
                   'alchohol',
                   'malic acid',
                   'ash',
                   'alcalinity of ash',
                   'magnesium',
                   'total phenols',
                   'flavanoids',
                   'nonflavanoid phenols',
                   'proanthocyanins',
                   'color intensity',
                   'hue',
                   'OD208',
                   'proline'
                   ]

print('class label:', np.unique(dat_wine['class label']))

class label: [1 2 3]


In [7]:
dat_wine.head()

class label  alchohol  malic acid   ash  alcalinity of ash  magnesium  \
0            1     14.23        1.71  2.43               15.6        127   
1            1     13.20        1.78  2.14               11.2        100   
2            1     13.16        2.36  2.67               18.6        101   
3            1     14.37        1.95  2.50               16.8        113   
4            1     13.24        2.59  2.87               21.0        118   

   total phenols  flavanoids  nonflavanoid phenols  proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   
3           3.85        3.49                  0.24             2.18   
4           2.80        2.69                  0.39             1.82   

   color intensity   hue  OD208  proline  
0             5.64  1.04   3.92     1065  
1             4.38  1.05   3.40     1050  
2             5.68  1.03   3.17     1185  
3             7.80  0.86   3.45     1480  
4             4.32  1.04   2.93      735

In [8]:
dat_wine.tail()

class label  alchohol  malic acid   ash  alcalinity of ash  magnesium  \
173            3     13.71        5.65  2.45               20.5         95   
174            3     13.40        3.91  2.48               23.0        102   
175            3     13.27        4.28  2.26               20.0        120   
176            3     13.17        2.59  2.37               20.0        120   
177            3     14.13        4.10  2.74               24.5         96   

     total phenols  flavanoids  nonflavanoid phenols  proanthocyanins  \
173           1.68        0.61                  0.52             1.06   
174           1.80        0.75                  0.43             1.41   
175           1.59        0.69                  0.43             1.35   
176           1.65        0.68                  0.53             1.46   
177           2.05        0.76                  0.56             1.35   

     color intensity   hue  OD208  proline  
173              7.7  0.64   1.74      740  
174              7.3  0.70   1.56      750  
175             10.2  0.59   1.56      835  
176              9.3  0.60   1.62      840  
177              9.2  0.61   1.60      560

In [9]:
from sklearn.model_selection import train_test_split
X, y = dat_wine.iloc[:, 1:].values, dat_wine.iloc[:, 0].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1, stratify=y)

### LinearDiscriminantAnalysis - Linear

In [10]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
cld = LinearDiscriminantAnalysis(store_covariance=True)
cld.fit(X_train, y_train)
y_train_pred = cld.predict(X_train)
y_test_pred = cld.predict(X_test)

In [11]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_train, y_train_pred))
print(accuracy_score(y_test, y_test_pred))

1.0
0.9814814814814815


In [12]:
print(cld.means_)

[[1.36785366e+01 2.02317073e+00 2.45439024e+00 1.71365854e+01
  1.05341463e+02 2.86219512e+00 3.02731707e+00 2.89268293e-01
  1.95634146e+00 5.52000000e+00 1.06878049e+00 3.15609756e+00
  1.11382927e+03]
 [1.22118000e+01 2.02160000e+00 2.27140000e+00 2.06780000e+01
  9.34000000e+01 2.21060000e+00 2.04080000e+00 3.84000000e-01
  1.58700000e+00 3.04620000e+00 1.04052000e+00 2.77820000e+00
  4.94980000e+02]
 [1.31745455e+01 3.56666667e+00 2.42181818e+00 2.13181818e+01
  1.00212121e+02 1.68151515e+00 7.77878788e-01 4.48787879e-01
  1.17727273e+00 7.49424242e+00 6.86363636e-01 1.68090909e+00
  6.49090909e+02]]


In [13]:
print(cld.xbar_)

[1.29529839e+01 2.43330645e+00 2.37193548e+00 1.96774194e+01
 9.91612903e+01 2.28524194e+00 2.03088710e+00 3.69919355e-01
 1.60008065e+00 5.04790323e+00 9.55612903e-01 2.61112903e+00
 7.40612903e+02]


In [14]:
print(cld.covariance_)

[[ 2.41615068e-01  3.84592439e-02 -5.24867188e-03 -2.30283993e-03
  -7.86881482e-02  1.11713745e-02  1.33361710e-02 -4.67113583e-04
   1.07053192e-02  1.77454884e-01  4.91173257e-04 -1.62968428e-02
   8.54595097e+00]
 [ 3.84592439e-02  8.32381396e-01  2.83227199e-02  4.00338741e-01
  -5.87202072e-01 -9.42715080e-03 -9.52135930e-03  7.35759507e-03
   4.69856098e-02 -1.45330075e-01 -4.62261537e-02  5.60318655e-02
  -2.84926307e+01]
 [-5.24867188e-03  2.83227199e-02  6.80395376e-02  4.91619869e-01
   5.99821043e-01  2.86110643e-02  5.76375339e-02  7.22680996e-03
   4.46800139e-03  5.20767053e-02  3.63662334e-03  2.06618862e-02
  -5.77687326e-02]
 [-2.30283993e-03  4.00338741e-01  4.91619869e-01  8.43814527e+00
   4.38952042e+00  1.97406921e-01  4.41501428e-01  4.11469745e-02
   1.66482453e-01  5.67441496e-02  9.41799084e-04  3.51744582e-01
   4.43128671e+00]
 [-7.86881482e-02 -5.87202072e-01  5.99821043e-01  4.38952042e+00
   1.48134957e+02  8.43279534e-01  1.38061621e+00 -3.28155413e-01


In [15]:
print(cld.intercept_)

[-67.42856949  36.51807749  -1.65569344]


In [16]:
print(cld.coef_)

[[ 3.31363106e+00 -1.50074077e-01  3.52564251e+00 -8.89161617e-01
   1.52342343e-02 -2.17293267e+00  5.03235438e+00  3.12123703e+00
  -6.92880046e-01 -8.98897257e-01  1.13259908e+00  4.18153518e+00
   1.45033209e-02]
 [-2.46059543e+00 -5.42764250e-01 -5.84259880e+00  3.74068465e-01
  -7.58334217e-03 -6.65402628e-01  2.13832396e+00  5.34725357e+00
   4.54059921e-01 -5.81709854e-01  3.80466959e+00 -3.06608438e-01
  -7.64653043e-03]
 [-3.88760666e-01  1.00882575e+00  4.47207870e+00  5.37945547e-01
  -7.43746969e-03  3.70789002e+00 -9.49220387e+00 -1.19797999e+01
   1.72881390e-01  1.99819031e+00 -7.17181945e+00 -4.73068243e+00
  -6.43362530e-03]]


In [17]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_test_pred))

[[18  0  0]
 [ 0 20  1]
 [ 0  0 15]]


In [18]:
print(cld.predict_proba(X_test[:5,]))

[[4.82027630e-11 9.53699966e-06 9.99990463e-01]
 [4.16120014e-19 1.20023483e-09 9.99999999e-01]
 [4.13851085e-15 2.75591141e-12 1.00000000e+00]
 [7.51250315e-05 9.99924835e-01 3.97700359e-08]
 [5.24688464e-07 9.99999475e-01 9.27968095e-16]]


### 이차판별분석 - QuadraticDiscriminantAnalysis

In [20]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
cqd = QuadraticDiscriminantAnalysis()
cqd.fit(X_train, y_train)
y_train_pred = cqd.predict(X_train)
y_test_pred = cqd.predict(X_test)

In [21]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_train, y_train_pred))
print(accuracy_score(y_test, y_test_pred))

1.0
0.9629629629629629


In [22]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_test_pred))

[[18  0  0]
 [ 1 20  0]
 [ 0  1 14]]


### Naive Bayesian

In [28]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()
mnb.fit(X, y)
print(mnb.predict(X[1:2,]))

[1]


In [29]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_test_pred = gnb.predict(X_test)

In [33]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_train, y_train_pred))
print(accuracy_score(y_test, y_test_pred))

1.0
0.9814814814814815
