## 다항단순베이즈모형
### 인위적인 자료
- 1~5 정수로 이루어진 6 x 20 행렬
- 표본의 개수 : 6
- 특성변수의 개수 : 20  

#### 1. 특성변수
- 특성변수의 개수 : 20
- 20개의 특성변수는 다항분포를 가정
- 특성변수의 값 : 해당 변수의 발생횟수를 의미  

#### 2. 목표변수 y
- 총 6개의 범주
- 범주 : 1, 2, 3, 4, 5, 6 라벨 부여

#### 범주별로 오직 하나의 표본만 있는 지극히 예제를 위한 예제

In [1]:
import numpy as np

X = np.random.randint(5, size=(6, 20))
y = np.array([1, 2, 3, 4, 5, 6])
print(X[:, :3])

[[1 0 2]
 [1 4 0]
 [4 1 1]
 [3 4 2]
 [2 3 0]
 [2 2 0]]


### 다항단순베이즈모형 - MultinomialNB
- MultinomialNB을 호출하여 시행
- 2번째 관측치에 대한 범주를 예측하는 프로그램

In [2]:
from sklearn.naive_bayes import MultinomialNB

mnb = MultinomialNB()
mnb.fit(X, y)
print(mnb.predict(X[1:2,]))

[2]
